#ifndef NPBC_STATUS_H
#define NPBC_STATUS_H

typedef enum {
    NPBC_STATUS_OK = 0,
    NPBC_STATUS_INVALID_ARGUMENT,
    NPBC_STATUS_INVALID_FORMAT,
    NPBC_STATUS_UNSUPPORTED,
    NPBC_STATUS_SIZE_OVERFLOW,
    NPBC_STATUS_ALLOCATION_FAILED,
    NPBC_STATUS_IO_FAILED,
    NPBC_STATUS_TRUNCATED_INPUT,
    NPBC_STATUS_INTEGRITY_FAILED,
    NPBC_STATUS_OUTPUT_EXISTS,
    NPBC_STATUS_INTERNAL_ERROR
} NpbcStatus;

const char *npbc_status_name(NpbcStatus status);

#endif
